# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

  create:
    tags:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
         ref: master
      - uses: actions/setup-python@v4
        with:
         python-version: '3.11.5' 

      # Runs a single command using the runners shell
      - name: checkout
        run: git clone -b main https://github.com/dortania/OpenCore-Legacy-Patcher.git



      # Runs a set of commands using the runners shell
      - name: patch 
        run: chmod +x gsed && python --version
      - name: patch 
        run:  ./gsed  -i  's/target_arch="universal2"/target_arch=None/g'   OpenCore-Legacy-Patcher/OpenCore-Patcher-GUI.spec
      - name: patch 
        run:  ./gsed  -i  's/ipc_control_port_options=0/ipc_control_port_options=0 vm_compressor=2/g' OpenCore-Legacy-Patcher/opencore_legacy_patcher/efi_builder/security.py
      - name: build
        run: cd OpenCore-Legacy-Patcher && pip3 install -r requirements.txt &&pip3 install pyinstaller && pip install charset-normalizer && python3  Build-Project.command   --reset-dmg-cache
      - name: test
        run : du -h OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app && rm OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app/Contents/Frameworks/*.dmg && mv -f  OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app/Contents/Resources/*.dmg OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app/Contents/Frameworks/ 

      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenCore-Patcher-TUI.app
          path: OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app
      - name: syncSrouce
        run: cp opencore_legacy_patcher/efi_builder/security.py security.py && git status &&git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" &&  git config --local user.name "github-actions[bot]" &&git add security.py &&git commit -m "sync build.py"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master    

 #
